import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Divider, HStack, Text, Center } from "@chakra-ui/react";
import { FaPlus } from "react-icons/fa6";
import { FaSearch } from "react-icons/fa";
import { CiCalendarDate } from "react-icons/ci";
import { IoStatsChart } from "react-icons/io5";
const QuickActions = ({ onTaskCreate }) => {
    return (_jsxs(Box, { bg: "linear-gradient(135deg, rgba(255,255,255,0.08), rgba(255,255,255,0.03))", border: "1px solid rgba(255,255,255,0.12)", boxShadow: "0 2px 8px rgba(0,0,0,0.5)", borderRadius: "md", w: "full", maxW: "1000px", h: "110px", mx: "auto", p: 3, children: [_jsx(Text, { fontWeight: "600", mb: 3, children: "Actions rapides" }), _jsxs(HStack, { spacing: 0, align: "center", h: "full", children: [_jsxs(HStack, { flex: "1", spacing: 3, px: 4, py: 2, mb: 5, cursor: "pointer", onClick: onTaskCreate, _hover: { bg: "blackAlpha.100", borderRadius: "md" }, children: [_jsx(Center, { boxSize: "1.8rem", bg: "blue.400", color: "white", borderRadius: "md", flexShrink: 0, children: _jsx(FaPlus, { size: 12 }) }), _jsx(Text, { fontWeight: "600", fontSize: "0.95rem", whiteSpace: { base: "normal", lg: "nowrap" }, overflow: "hidden", textOverflow: "ellipsis", mt: 3, children: "Cr\u00E9er une nouvelle t\u00E2che" })] }), _jsx(Divider, { orientation: "vertical", alignSelf: "center", borderColor: "gray.700", height: "60%", mb: 10 }), _jsxs(HStack, { flex: "1", spacing: 3, px: 4, py: 2, mb: 5, cursor: "pointer", _hover: { bg: "blackAlpha.100", borderRadius: "md" }, children: [_jsx(Center, { boxSize: "1.8rem", bg: "green.400", color: "white", borderRadius: "md", flexShrink: 0, children: _jsx(FaSearch, { size: 12 }) }), _jsx(Text, { fontWeight: "600", fontSize: "0.95rem", whiteSpace: { base: "normal", lg: "nowrap" }, overflow: "hidden", textOverflow: "ellipsis", mt: 3, children: "Rechercher un employ\u00E9" })] }), _jsx(Divider, { orientation: "vertical", alignSelf: "center", borderColor: "gray.700", height: "60%", mb: 10 }), _jsxs(HStack, { flex: "1", spacing: 3, px: 4, py: 2, mb: 5, cursor: "pointer", _hover: { bg: "blackAlpha.100", borderRadius: "md" }, children: [_jsx(Center, { boxSize: "1.8rem", bg: "purple.400", color: "white", borderRadius: "md", flexShrink: 0, children: _jsx(CiCalendarDate, { size: 16 }) }), _jsx(Text, { fontWeight: "600", fontSize: "0.95rem", whiteSpace: { base: "normal", lg: "nowrap" }, overflow: "hidden", textOverflow: "ellipsis", mt: 3, children: "Demande de cong\u00E9" })] }), _jsx(Divider, { orientation: "vertical", alignSelf: "center", borderColor: "gray.700", height: "60%", mb: 10 }), _jsxs(HStack, { flex: "1", spacing: 3, px: 4, py: 2, mb: 5, cursor: "pointer", _hover: { bg: "blackAlpha.100", borderRadius: "md" }, children: [_jsx(Center, { boxSize: "1.8rem", bg: "orange.400", color: "white", borderRadius: "md", flexShrink: 0, children: _jsx(IoStatsChart, { size: 14 }) }), _jsx(Text, { fontWeight: "600", fontSize: "0.95rem", whiteSpace: { base: "normal", lg: "nowrap" }, overflow: "hidden", textOverflow: "ellipsis", mt: 3, children: "G\u00E9n\u00E9rer un rapport" })] })] })] }));
};
export default QuickActions;
