import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Box, Button, Card, Flex, HStack, Text, VStack, } from "@chakra-ui/react";
import { FaRegArrowAltCircleRight } from "react-icons/fa";
import { BsFillPeopleFill } from "react-icons/bs";
import { BsBoxSeamFill } from "react-icons/bs";
// @ts-ignore
import Logo from "../components/Logo";
const AdminPage = () => {
    return (_jsxs(Flex, { direction: "column", height: "100vh", width: "100vw", bgGradient: "radial(#47370b, #061962)", children: [_jsx(Box, { marginTop: "3.2rem", marginLeft: "8px", children: _jsx(Logo, { text: "Gestion de stock et de personnel" }) }), _jsxs(HStack, { spacing: "45px", position: "relative", top: "150px", left: "300px", children: [_jsx(Card, { backgroundColor: "#08162b", height: "380px", width: "380px", borderWidth: "0.5px", borderColor: "#c9990a", borderRadius: "20px", children: _jsxs(VStack, { children: [_jsx(Box, { position: "relative", top: "40px", borderWidth: "1px", padding: "20px", borderRadius: "60px", borderColor: "#c9990a", children: _jsx(BsFillPeopleFill, { color: "#c9990a", size: "80px" }) }), _jsxs(Box, { position: "relative", top: "55px", left: "13px", children: [_jsx(Text, { color: "#ffffff", fontSize: "24px", fontWeight: "700", children: "Module personnel" }), _jsx(Text, { color: "#ffffff", position: "relative", bottom: "18px", children: "G\u00E9rez vos employ\u00E9s,pr\u00E9sences," }), _jsx(Text, { color: "#ffffff", position: "relative", left: "10px", bottom: "30px", children: "cong\u00E9s et fiches de paye" })] }), _jsx(Link, { to: "/employees_admin", children: _jsxs(Button, { color: "#41340b", background: "#c9990a", fontSize: "20px", padding: "25px", position: "absolute", left: "62px", bottom: "14px", borderRadius: "15px", width: "280px", _hover: { color: "#41340b" }, children: [_jsx(Text, { position: "relative", top: "7px", marginRight: "20px", children: "Acceder au module" }), _jsx(FaRegArrowAltCircleRight, {})] }) })] }) }), _jsx(Card, { height: "380px", width: "380px", backgroundColor: "#08162b", borderWidth: "0.5px", borderColor: "#0d6efd", borderRadius: "20px", children: _jsxs(VStack, { children: [_jsx(Box, { position: "relative", top: "40px", borderWidth: "1px", padding: "20px", borderRadius: "60px", borderColor: "#0d6efd", children: _jsx(BsBoxSeamFill, { color: "#0d6efd", size: "80px" }) }), _jsxs(Box, { position: "relative", top: "55px", left: "35px", children: [_jsx(Text, { color: "#ffffff", fontSize: "24px", fontWeight: "700", children: "Module stock" }), _jsx(Text, { color: "#ffffff", position: "relative", right: "20px", bottom: "18px", children: "G\u00E9rez vos produits,entr\u00E9es," }), _jsx(Text, { color: "#ffffff", position: "relative", right: "20px", bottom: "30px", children: "sorties,stock et inventaires" })] }), _jsx(Link, { to: "/admin", children: _jsxs(Button, { color: "#41340b", background: "#0d6efd", fontSize: "21px", padding: "25px", textColor: "#ffffff", position: "absolute", left: "65px", bottom: "14px", borderRadius: "15px", width: "280px", _hover: { color: "#41340b", textColor: "#ffffff" }, children: [_jsx(Text, { position: "relative", top: "7px", marginRight: "20px", children: "Acceder au module" }), " ", _jsx(FaRegArrowAltCircleRight, {})] }) })] }) })] })] }));
};
export default AdminPage;
