import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Box, Button, Flex, HStack, Text, VStack, } from "@chakra-ui/react";
import { FaRegArrowAltCircleRight } from "react-icons/fa";
import { BsFillPeopleFill } from "react-icons/bs";
import { BsBoxSeamFill } from "react-icons/bs";
// @ts-ignore
import Logo from "../components/Logo";
const AdminPage = () => {
    return (_jsxs(Flex, { direction: "column", height: "100vh", width: "100vw", bg: "linear-gradient(180deg, #F8F9FB 0%, #EEF2F7 100%)", children: [_jsx(Box, { marginTop: "2.2rem", marginLeft: "8px", children: _jsx(Logo, { text: "Gestion de stock et de personnel" }) }), _jsxs(HStack, { spacing: "40px", justify: "center", align: "center", flex: "1", position: "relative", bottom: "2rem", children: [_jsxs(VStack, { bg: "#FFFFFF", height: "380px", width: "380px", border: "1px solid", borderColor: "#D1D9E0", borderRadius: "12px", boxShadow: "\n          0 8px 20px rgba(0,0,0,0.12),\n          0 0 20px rgba(242, 183, 5, 0.35)", transition: "all 0.2s ease", children: [_jsx(Box, { position: "relative", top: "2.5rem", borderWidth: "2px", padding: "20px", borderRadius: "60px", borderColor: "#0078D4", children: _jsx(BsFillPeopleFill, { color: "#0078D4", size: "3.5rem" }) }), _jsxs(Box, { position: "relative", top: "3.3rem", left: "35px", children: [_jsx(Text, { color: "#1F2937", fontSize: "1.5rem", fontWeight: "600", children: "Module personnel" }), _jsx(Text, { color: "#6B7280", fontSize: "1.2rem", position: "relative", right: "1.2rem", children: "G\u00E9rez vos employ\u00E9s, pr\u00E9sences," }), _jsx(Text, { color: "#6B7280", fontSize: "1.2rem", position: "relative", left: "0.5rem", bottom: "0.8rem", children: "cong\u00E9s et fiches de paye" })] }), _jsx(Link, { to: "/employees_admin", children: _jsxs(Button, { bg: "#0078D4", color: "white", fontSize: "1rem", height: "52px", width: "280px", fontWeight: "600", position: "relative", top: "2rem", borderRadius: "6px", _hover: {
                                        bg: "#106EBE",
                                    }, _active: {
                                        bg: "#005A9E",
                                    }, children: [_jsx(Text, { position: "relative", top: "0.5rem", marginRight: "1.2rem", fontSize: "1.1rem", children: "Acceder au module" }), _jsx(FaRegArrowAltCircleRight, {})] }) })] }), _jsxs(VStack, { bg: "#FFFFFF", height: "380px", width: "380px", border: "1px solid", borderColor: "#D1D9E0", borderRadius: "12px", boxShadow: "\n          0 8px 20px rgba(0,0,0,0.12),\n          0 0 20px rgba(242, 183, 5, 0.35)", transition: "all 0.2s ease", children: [_jsxs(Box, { position: "relative", top: "2.5rem", borderWidth: "1px", padding: "20px", borderRadius: "60px", borderColor: "#107C10", children: [_jsx(BsBoxSeamFill, { color: "#107C10", size: "4rem" }), " "] }), _jsxs(Box, { position: "relative", top: "3.3rem", left: "35px", children: [_jsx(Text, { color: "#1F2937", fontSize: "24px", fontWeight: "600", children: "Module stock" }), _jsx(Text, { color: "#6B7280", fontSize: "1.2rem", position: "relative", right: "1.2rem", bottom: "0.5rem", children: "G\u00E9rez vos produits,entr\u00E9es," }), _jsx(Text, { color: "#6B7280", fontSize: "1.2rem", position: "relative", right: "1rem", bottom: "1.3rem", children: "sorties,stock et inventaires" })] }), _jsx(Link, { to: "/admin", children: _jsxs(Button, { bg: "#107C10", color: "white", fontSize: "16px", fontWeight: "600", height: "52px", width: "280px", position: "relative", top: "1.5rem", borderRadius: "6px", _hover: {
                                        bg: "#0E6E0E",
                                    }, children: [_jsx(Text, { position: "relative", top: "0.5rem", marginRight: "1.2rem", fontSize: "1.1rem", children: "Acceder au module" }), " ", _jsx(FaRegArrowAltCircleRight, {})] }) })] })] })] }));
};
export default AdminPage;
