import {
  Badge,
  Box,
  Button,
  Flex,
  HStack,
  IconButton,
  MenuButton,
  MenuItem,
  MenuList,
  Menu,
  Table,
  TableContainer,
  Tbody,
  Td,
  Text,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { FaSyncAlt } from "react-icons/fa";
import { IoSettings } from "react-icons/io5";
import { PiDotsThreeOutlineVerticalDuotone } from "react-icons/pi";
import { MdOutlineDeleteForever } from "react-icons/md";
import { IoIosRemoveCircleOutline } from "react-icons/io";
import { Link, useNavigate } from "react-router-dom";
import User from "../../../common/types/User";
import { PayrollRun } from "../../../common/types/payroll/Payroll";
import useAdminUser from "../../../store/auth.store";
import { getPayrollPeriod } from "../../util/getPayrollPeriod";

export default function PayrollPage() {
  const [payrollRuns, setPayrollRuns] = useState<PayrollRun[]>([]);
  const [loading, setLoading] = useState(false);
  const user: Omit<User, "password" | "notes"> = useAdminUser(
    (store) => store.adminUser
  );
  const navigate = useNavigate();

  useEffect(() => {
    loadPayrollRun();
  }, []);

  const loadPayrollRun = async () => {
    try {
      const payrollRuns = await window.electron.payrollRun.getPayrollRuns();
      console.log("FETCHED PAYROLL RUNS", payrollRuns);
      setPayrollRuns(payrollRuns);
    } catch (e) {
      console.error("AN ERROR OCCURED WHILE LOADING PAYROLL RUNS", e);
    }
  };

  const handlePayrollGeneration = async () => {
    console.log("GENERATED BY ADMIN USER", user);
    try {
      const payroll_results =
        await window.electron.payrollRun.createPayrollDraft(user);
      loadPayrollRun();
      console.log("PAYROLL RESULTS", payroll_results);
    } catch (e) {
      console.error("AN ERROR OCCURED WHILE GENERATING PAYROLL", e);
    }
  };
  //Payroll sync and refresh
  const handlePayrollSync = async () => {
    try {
      setLoading(true);
      const result = await window.electron.sync();
      if (result.success) {
        console.log("SYNC COMPLETED");
        loadPayrollRun();
      } else {
        console.error(result.message);
      }
    } catch (e) {
      console.error("AN ERROR OCCURED WHILE SYNCING", e);
    } finally {
      setLoading(false);
    }
  };

  const withdraw = async (_id: string) => {
    try {
      const results = await window.electron.payrollRun.returnToDraft(_id);
      console.log("WITHDRAW RESULTS", results);
      loadPayrollRun();
    } catch (e) {
      console.error("AN ERROR OCCURED WHILE WITHDRAWING PAYROLL", e);
    }
  };

  const handlePayrollCancellation = async (_id: string) => {
    if (!_id) return;
    try {
      const results = await window.electron.payrollRun.cancelPayroll(_id, user);
      console.log("CANCELLATION RESULTS", results);
      loadPayrollRun();
    } catch (e) {
      console.error("AN ERROR OCCURED DURING CANCELLATION", e);
    }
  };

  const handleDelete = async (_id: string) => {
    try {
      const results = await window.electron.payrollRun.deletePayrollRun(_id);
      console.log("DELETE RESULTS", results);
      loadPayrollRun();
    } catch (e) {
      console.error("AN ERROR OCCURED WHILE DELETING PAYROLL", e);
    }
  };

  const statusColor = {
    BROUILLON: "#e6b800",
    VERIFICATION: "#1a53ff",
    APPROUVÉ: "green",
    PAYÉ: "purple",
    ANNULÉ: "red",
  } as const;

  return (
    <Flex direction="column" width="100%">
      <Flex width="100%" justify="space-between">
        <Box>
          <HStack>
            <Text
              color="#1F2937"
              fontSize="clamp(1.3rem, 1vw + 0.8rem, 1.4rem)"
              fontWeight="700"
              ml="1rem"
              mt="0.7rem"
            >
              Fiches de paye
            </Text>
            <Button
              bg="transparent"
              isLoading={loading}
              color="gray.800"
              _hover={{ bg: "transparent" }}
              fontSize="1rem"
              position="relative"
              bottom="0.2rem"
              right="1rem"
              onClick={handlePayrollSync}
            >
              <FaSyncAlt />
            </Button>
          </HStack>
          <Text
            fontWeight="500"
            fontSize="clamp(1rem, 1vw + 0.8rem, 1.1rem)"
            color="gray.500"
            position="relative"
            bottom="1.4rem"
            left="1rem"
          >
            Gérez les fiches de payes
          </Text>
        </Box>

        <Button
          colorScheme="blue"
          mr="2rem"
          mt="1.2rem"
          onClick={handlePayrollGeneration}
        >
          Générer fiches de paye
        </Button>

        <Box mt="1rem" mr="2rem">
          <Link to="/employees_admin/payroll/settings">
            <IoSettings fontSize="1.9rem" />
          </Link>
        </Box>
      </Flex>
      <Box ml="5rem" mt="3rem">
        {payrollRuns.length === 0 ? (
          <Text
            position="relative"
            top="12rem"
            left="15rem"
            color="gray.700"
            fontSize="2rem"
            fontWeight="500"
          >
            Pas de fiches de payes à afficher
          </Text>
        ) : (
          <TableContainer
            maxWidth="70vw"
            maxHeight="70vh"
            borderWidth="1px"
            borderRadius="lg"
            overflowY="auto"
          >
            <Table variant="simple" size="md">
              <Thead position="sticky" top={0} zIndex={1} bg="gray.50">
                <Tr>
                  <Th>Période</Th>
                  <Th>Statut</Th>
                  <Th>Créee par</Th>
                  <Th>Date de création</Th>
                  {user?.role === "MANAGER" ? <Th>Actions</Th> : null}
                </Tr>
              </Thead>

              <Tbody>
                {payrollRuns.map((run) => (
                  <Tr key={run._id}>
                    <Td
                      cursor="pointer"
                      _hover={{ bg: "transparent" }}
                      transition="background 0.2s"
                      onClick={() =>
                        navigate(`/employees_admin/payroll/details/${run._id}`)
                      }
                    >
                      Du{" "}
                      {run?.month && run?.year
                        ? getPayrollPeriod(run.month, run.year)
                        : ""}
                    </Td>

                    <Td>
                      <Badge
                        bg={statusColor[run.status]}
                        color="#ffffff"
                        fontSize="14px"
                      >
                        {run.status}
                      </Badge>
                    </Td>

                    <Td>{run.generatedByName}</Td>

                    <Td>
                      {run.createdAt
                        ? new Date(run.createdAt).toLocaleDateString("fr-FR")
                        : "-"}
                    </Td>
                    {user?.role === "MANAGER" ? (
                      <Td>
                        <Menu placement="bottom">
                          <MenuButton
                            mb={10}
                            as={IconButton}
                            icon={
                              <PiDotsThreeOutlineVerticalDuotone size="1.8rem" />
                            }
                            color="gray.700"
                            variant="ghost"
                            borderRadius="full"
                            _hover={{
                              bg: "transparent",
                            }}
                            _expanded={{
                              bg: "transparent",
                            }}
                            aria-label="Actions"
                            position="relative"
                            top="1rem"
                          />

                          <MenuList
                            bg="#ffffff"
                            border="1px solid #2A3D70"
                            borderRadius="14px"
                            minW="170px"
                            p="6px"
                            boxShadow="0 8px 30px rgba(0,0,0,0.35)"
                          >
                            {run.status !== "BROUILLON" &&
                            run.status !== "ANNULÉ" ? (
                              <MenuItem
                                height="10px"
                                ml="1rem"
                                mb="0.2rem"
                                pt={2}
                                icon={
                                  <IoIosRemoveCircleOutline
                                    color="orange"
                                    size="1.2rem"
                                  />
                                }
                                bg="transparent"
                                color="gray.800"
                                borderRadius="10px"
                                _hover={{
                                  bg: "transparent",
                                }}
                                onClick={() => withdraw(run._id)}
                              >
                                Retirer
                              </MenuItem>
                            ) : null}

                            {run.status === "BROUILLON" ? (
                              <MenuItem
                                height="20px"
                                mb={2}
                                pt={3}
                                icon={
                                  <MdOutlineDeleteForever
                                    color="red"
                                    size="1.5rem"
                                  />
                                }
                                bg="transparent"
                                color="gray.800"
                                borderRadius="10px"
                                _hover={{
                                  bg: "transparent",
                                }}
                                onClick={() =>
                                  handlePayrollCancellation(run._id)
                                }
                              >
                                Annuler
                              </MenuItem>
                            ) : null}

                            {run.status === "ANNULÉ" ? (
                              <MenuItem
                                height="20px"
                                mb={2}
                                pt={3}
                                icon={
                                  <MdOutlineDeleteForever
                                    color="red"
                                    size="1.5rem"
                                  />
                                }
                                bg="transparent"
                                color="gray.800"
                                borderRadius="10px"
                                _hover={{
                                  bg: "transparent",
                                }}
                                onClick={() => handleDelete(run._id)}
                              >
                                Supprimer
                              </MenuItem>
                            ) : null}
                          </MenuList>
                        </Menu>
                      </Td>
                    ) : null}
                  </Tr>
                ))}
              </Tbody>
            </Table>
          </TableContainer>
        )}
      </Box>
    </Flex>
  );
}
