import { Box, Flex, Text, HStack, Button } from "@chakra-ui/react";
import { Link } from "react-router-dom";
import { IoSettings } from "react-icons/io5";
import { FaSyncAlt } from "react-icons/fa";
import { useEffect, useState } from "react";
import useAdminUser from "../../../store/auth.store";
import User from "../../../common/types/User";
import Payroll, { PayrollRun } from "../../../common/types/payroll/Payroll";
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from "@chakra-ui/react";

export default function PayrollPage() {
  const [payrollRuns, setPayrollRuns] = useState<PayrollRun[]>([]);
  const [loading, setLoading] = useState(false);
  const user: Omit<User, "password" | "notes"> = useAdminUser(
    (store) => store.adminUser
  );

  useEffect(() => {
    loadPayrollRun();
  }, []);

  const loadPayrollRun = async () => {
    const payrollRuns = await window.electron.payrollRun.getPayrollRuns();
    console.log("FETCHED PAYROLL RUNS", payrollRuns);
    setPayrollRuns(payrollRuns);
  };

  const handlePayrollGeneration = async () => {
    console.log("GENERATED BY ADMIN USER", user);
    try {
      const payroll_results =
        await window.electron.payrollRun.createPayrollDraft(user);
      loadPayrollRun();
      console.log("PAYROLL RESULTS", payroll_results);
    } catch (e) {
      console.error("AN ERROR OCCURED WHILE GENERATING PAYROLL", e);
    }
  };
  //Payroll sync and refresh
  const handlePayrollSync = async () => {
    // try {
    //   setLoading(true);
    //   const result = await window.electron.sync();
    //   if (result.success) {
    //     console.log("Sync completed");
    //     const leaves = await window.electron.leave.getLeaveByMonth(
    //       submissionMonth
    //     );
    //     setLeaves(leaves);
    //     console.log(
    //       `Fetched leaves for the month of ${submissionMonth}:${leaves}`
    //     );
    //   } else {
    //     console.error(result.message);
    //   }
    // } finally {
    //   setLoading(false);
    // }
  };

  return (
    <Flex direction="column" width="100%">
      <Flex width="100%" justify="space-between">
        <Box>
          <HStack>
            <Text
              color="#1F2937"
              fontSize="clamp(1.3rem, 1vw + 0.8rem, 1.4rem)"
              fontWeight="700"
              ml="0.5rem"
              mt="0.7rem"
            >
              Fiches de paye
            </Text>
            <Button
              bg="transparent"
              isLoading={loading}
              color="gray.800"
              _hover={{ bg: "transparent" }}
              fontSize="1rem"
              position="relative"
              bottom="0.2rem"
              right="1rem"
              onClick={handlePayrollSync}
            >
              <FaSyncAlt />
            </Button>
          </HStack>
          <Text
            fontWeight="500"
            left="0.45rem"
            fontSize="clamp(1rem, 1vw + 0.8rem, 1.1rem)"
            color="gray.500"
            position="relative"
            bottom="1.4rem"
          >
            Gérez les fiches de payes
          </Text>
        </Box>

        <Button mt="2rem" onClick={handlePayrollGeneration}>
          Generer fiches de paye
        </Button>

        <Box mt="1rem" mr="2rem">
          <Link to="/employees_admin/payroll/settings">
            <IoSettings fontSize="1.7rem" />
          </Link>
        </Box>
      </Flex>
      <Box ml="2rem" mt="3rem">
        <TableContainer
          width="50vw"
          borderWidth="1px"
          borderRadius="lg"
          overflowX="auto"
        >
          <Table variant="simple" size="md">
            <Thead>
              <Tr>
                <Th>Période</Th>
                <Th>Statut</Th>
                <Th>Généré par</Th>
                <Th>Date de génération</Th>
                {/* <Th>Approuvé par</Th>
                <Th>Date d'approbation</Th>
                <Th>Payé par</Th>
                <Th>Date de paiement</Th>
                <Th>Annulé par</Th>
                <Th>Date d'annulation</Th> */}
              </Tr>
            </Thead>

            <Tbody>
              {payrollRuns.map((run) => (
                <Tr
                  key={run._id}
                  cursor="pointer"
                  _hover={{ bg: "transparent" }}
                  transition="background 0.2s"
                  // onClick={() => navigate(`/payroll/${run._id}`)}
                >
                  <Td>
                    {run.month.toString().padStart(2, "0")}/{run.year}
                  </Td>

                  <Td>
                    {/* Status badge here */}
                    {run.status}
                  </Td>

                  <Td>{run.generatedByName}</Td>

                  <Td>
                    {run.createdAt
                      ? new Date(run.createdAt).toLocaleDateString("fr-FR")
                      : "-"}
                  </Td>

                  {/* <Td>{run.approvedBy ?? "-"}</Td>

                  <Td>
                    {run.approvedAt
                      ? new Date(run.approvedAt).toLocaleString()
                      : "-"}
                  </Td> */}

                  {/* <Td>{run.paidBy ?? "-"}</Td>

                  <Td>
                    {run.paidAt ? new Date(run.paidAt).toLocaleString() : "-"}
                  </Td> */}
                  {/* 
                  <Td>{run.cancelledBy ?? "-"}</Td>

                  <Td>
                    {run.cancelledAt
                      ? new Date(run.cancelledAt).toLocaleString()
                      : "-"}
                  </Td> */}
                </Tr>
              ))}
            </Tbody>
          </Table>
        </TableContainer>
      </Box>
    </Flex>
  );
}
