import { Box, Flex, Text, HStack, Button, Badge } from "@chakra-ui/react";
import { Link } from "react-router-dom";
import { IoSettings } from "react-icons/io5";
import { FaSyncAlt } from "react-icons/fa";
import { useEffect, useState } from "react";
import useAdminUser from "../../../store/auth.store";
import User from "../../../common/types/User";
import Payroll, { PayrollRun } from "../../../common/types/payroll/Payroll";
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from "@chakra-ui/react";
import { useNavigate } from "react-router-dom";
import { getPayrollPeriod } from "../../util/getPayrollPeriod";

export default function PayrollPage() {
  const [payrollRuns, setPayrollRuns] = useState<PayrollRun[]>([]);
  const [loading, setLoading] = useState(false);
  const user: Omit<User, "password" | "notes"> = useAdminUser(
    (store) => store.adminUser
  );
  const navigate = useNavigate();

  useEffect(() => {
    loadPayrollRun();
  }, []);

  const loadPayrollRun = async () => {
    const payrollRuns = await window.electron.payrollRun.getPayrollRuns();
    console.log("FETCHED PAYROLL RUNS", payrollRuns);
    setPayrollRuns(payrollRuns);
  };

  const handlePayrollGeneration = async () => {
    console.log("GENERATED BY ADMIN USER", user);
    try {
      const payroll_results =
        await window.electron.payrollRun.createPayrollDraft(user);
      loadPayrollRun();
      console.log("PAYROLL RESULTS", payroll_results);
    } catch (e) {
      console.error("AN ERROR OCCURED WHILE GENERATING PAYROLL", e);
    }
  };
  //Payroll sync and refresh
  const handlePayrollSync = async () => {
    // try {
    //   setLoading(true);
    //   const result = await window.electron.sync();
    //   if (result.success) {
    //     console.log("Sync completed");
    //     const leaves = await window.electron.leave.getLeaveByMonth(
    //       submissionMonth
    //     );
    //     setLeaves(leaves);
    //     console.log(
    //       `Fetched leaves for the month of ${submissionMonth}:${leaves}`
    //     );
    //   } else {
    //     console.error(result.message);
    //   }
    // } finally {
    //   setLoading(false);
    // }
  };

  const statusColor = {
    BROUILLON: "#e6b800",
    VERIFICATION: "#1a53ff",
    APPROUVÉ: "green",
    PAYÉ: "purple",
    ANNULÉ: "red",
  } as const;

  return (
    <Flex direction="column" width="100%">
      <Flex width="100%" justify="space-between">
        <Box>
          <HStack>
            <Text
              color="#1F2937"
              fontSize="clamp(1.3rem, 1vw + 0.8rem, 1.4rem)"
              fontWeight="700"
              ml="1rem"
              mt="0.7rem"
            >
              Fiches de paye
            </Text>
            <Button
              bg="transparent"
              isLoading={loading}
              color="gray.800"
              _hover={{ bg: "transparent" }}
              fontSize="1rem"
              position="relative"
              bottom="0.2rem"
              right="1rem"
              onClick={handlePayrollSync}
            >
              <FaSyncAlt />
            </Button>
          </HStack>
          <Text
            fontWeight="500"
            fontSize="clamp(1rem, 1vw + 0.8rem, 1.1rem)"
            color="gray.500"
            position="relative"
            bottom="1.4rem"
            left="1rem"
          >
            Gérez les fiches de payes
          </Text>
        </Box>

        <Button
          colorScheme="blue"
          mr="2rem"
          mt="1.2rem"
          onClick={handlePayrollGeneration}
        >
          Générer fiches de paye
        </Button>

        <Box mt="1rem" mr="2rem">
          <Link to="/employees_admin/payroll/settings">
            <IoSettings fontSize="1.7rem" />
          </Link>
        </Box>
      </Flex>
      <Box ml="5rem" mt="3rem">
        {payrollRuns.length === 0 ? (
          <Text
            position="relative"
            top="12rem"
            left="20rem"
            color="gray.700"
            fontSize="2.1rem"
            fontWeight="500"
          >
            Pas de fiches de payes à afficher
          </Text>
        ) : (
          <TableContainer
            width="60vw"
            borderWidth="1px"
            borderRadius="lg"
            overflowX="auto"
            overflowY="auto"
          >
            <Table variant="simple" size="md">
              <Thead>
                <Tr>
                  <Th>Période</Th>
                  <Th>Statut</Th>
                  <Th>Créee par</Th>
                  <Th>Date de création</Th>
                </Tr>
              </Thead>

              <Tbody>
                {payrollRuns.map((run) => (
                  <Tr
                    key={run._id}
                    cursor="pointer"
                    _hover={{ bg: "transparent" }}
                    transition="background 0.2s"
                    onClick={() =>
                      navigate(`/employees_admin/payroll/details/${run._id}`)
                    }
                  >
                    <Td>
                      Du{" "}
                      {run?.month && run?.year
                        ? getPayrollPeriod(run.month, run.year)
                        : ""}
                    </Td>

                    <Td>
                      <Badge
                        bg={statusColor[run.status]}
                        color="#ffffff"
                        fontSize="14px"
                      >
                        {run.status}
                      </Badge>
                    </Td>

                    <Td>{run.generatedByName}</Td>

                    <Td>
                      {run.createdAt
                        ? new Date(run.createdAt).toLocaleDateString("fr-FR")
                        : "-"}
                    </Td>
                  </Tr>
                ))}
              </Tbody>
            </Table>
          </TableContainer>
        )}
      </Box>
    </Flex>
  );
}
